### ISSUE TITLE
OpenVZ is not supported. Script needs to detect it.

### ISSUE THREAD

**Issue by GuBo88** [l-n-s/wireguard-install#15]
Hi,

I used your script on a VPS with CentOS 7. The installation runs smooth. I also can connect from the Wireguard iOS App. But I can't connect to any webpage. By manually starting up Wireguard I run into the following problem:

root@GuBo ~]# wg-quick up wg0
[#] ip link add wg0 type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0

Can you help?
Thanks

**Comment by LiveChief** [comment]
is this a client side error or a server side error??

**Comment by GuBo88** [comment]
Dear,  

World expect server. The WireGuard App on iOS works with another (commercial) Wireguard service. Also the App shows me the connection is established. And configuration is done by the generated QR code. Would I help if you can login to the VPS Server?  

I can provide you with the login data by email.  

Thanks  
Thomas


The life is too short to drink a bad wine.

**Comment by LiveChief** [comment]
https://gist.github.com/LiveChief/25da2f6733711f48930dcdc8decfa986

Take a look at this.

**Comment by GuBo88** [comment]
On Debian 9.2 (64-bit) Minimal and following the above steps I get the following error:
/usr/lib/wireguard_install.sh: line 146: /etc/iptables/rules.v4: No such file or directory
Failed to enable unit: File wg-quick@wg0.service: No such file or directory
Failed to start wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

Thanks

**Comment by l-n-s** [comment]
@GuBo88 looks like your server has problems with wireguard kernel module. Is it a virtual server? Does it allow kernel modules to be loaded?

**Comment by GuBo88** [comment]
It's a virtual server (https://www.liteserver.nl). I'm not sure if it allow kernel modules to be installed.

**Comment by l-n-s** [comment]
@GuBo88 good, is it KVM or OpenVZ?

**Comment by GuBo88** [comment]
OpenVZ and installing Kernel modules is not possible in OpenVZ at Liteserver. I need a KVM VPS from them.

**Comment by GuBo88** [comment]
Any way to run Wireguard on OpneVZ?

**Comment by l-n-s** [comment]
You can install a userspace version of Wireguard, but it performs a lot worse than the kernel module. I'd suggest changing your VPS plan to KVM.

**Comment by hexicans** [comment]
Hello,
Seem now it's supported, no ? https://wiki.openvz.org/VPN_using_Wireguard

**Comment by l-n-s** [comment]
No, it's not. This instruction is for hosting providers, not for clients.

**Comment by hexicans** [comment]
If I configure host and container, I can run a wireguard server I think
