### ISSUE TITLE
line 176: -4: substring expression < 0

### ISSUE THREAD

**Issue by Dubzer** [l-n-s/wireguard-install#16]
Using: almost clear Ubuntu 18 on AWS
User: newbie in Linux =) 

Here's a log what I do:

https://pastebin.com/rwiWquMU

**Comment by KoopaTroopas** [comment]
Yeah, I just saw your previous comment.  Removing the wg-0.conf file did the trick

**Comment by LiveChief** [comment]
Delete the VM and create a new one.

**Comment by Dubzer** [comment]
Removing Wireguard config helped, thx
