### ISSUE TITLE
Error in Ubuntu line 152

### ISSUE THREAD

**Issue by GuBo88** [l-n-s/wireguard-install#18]
One one of my two KVM with Ubuntu 18.04 the installation  stopped with an error:wireguard-install.sh: line 152: /etc/iptables/rules.v4: No such file or directory
Failed to enable unit: Unit file wg-quick@wg0.service does not exist.
Failed to start wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

**Comment by l-n-s** [comment]
Please, confirm that you are running the original script https://github.com/l-n-s/wireguard-install/blob/master/wireguard-install.sh

NOT the [script from the comments in your previous issue](https://github.com/l-n-s/wireguard-install/issues/15#issuecomment-458287543), it will not work.

**Comment by LiveChief** [comment]
> Please, confirm that you are running the original script https://github.com/l-n-s/wireguard-install/blob/master/wireguard-install.sh
> 
> NOT the [script from the comments in your previous issue](https://github.com/l-n-s/wireguard-install/issues/15#issuecomment-458287543), it will not work.

hey, the original script dosen't work on, vultr / digital ocean / google cloud
the modified script works on those...

plus IPV6 from this script dosent work..
