### ISSUE TITLE
Clients lose connection

### ISSUE THREAD

**Issue by mikelpzm** [l-n-s/wireguard-install#35]
It works perfect out of the box, but when the client has been connected for some seconds it appears to lose connection and then connects again.

Some configurantion needed in the server to fix this?

**Comment by l-n-s** [comment]
> but when the client has been connected for some seconds it appears to lose connection and then connects again
Not sure what do you mean by this, can you explain in more details?

**Comment by mikelpzm** [comment]
Sure! I'm able to connect using the VPN and it works fine. I keep surfing the web and opening pages... And then it suddenly stops loading webs and I lose connection for a while. Then it recovers after a few seconds and pages begin to load again. 

If I can provide you with any log or so... Glad to do it.

**Comment by l-n-s** [comment]
OK, it seems like an issue with wireguard itself, but I can't help you with it. 

This is not a wireguard repository, it is just installer helper script for it. Hope you understand.
