### ISSUE TITLE
resolvconf not installed ubuntu18

### ISSUE THREAD

**Issue by K4TAY** [l-n-s/wireguard-install#37]
/usr/bin/wg-quick: line 31: resolvconf: command not found

add this to your install dependencies

**Comment by K4TAY** [comment]
On the client when running

sudo wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip address add 10.9.0.4/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a tun.wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -6 route add ::/0 dev wg0 table 51820
[#] ip -6 rule add not fwmark 51820 table 51820
[#] ip -6 rule add table main suppress_prefixlength 0
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820

and then the box goes offline.  Upon reboot from a console you see this

PKCS#7 signature not signed with a trusted key

**Comment by l-n-s** [comment]
>/usr/bin/wg-quick: line 31: resolvconf: command not found
Does that happen on the client?
