### ISSUE TITLE
If my IP banned from gfw, wireguard can still working?

### ISSUE THREAD

**Issue by TKBSTMYN** [l-n-s/wireguard-install#38]
Hello, I'm guy from China.
Before long Im using v2ray.But that make me ip dead.
the internet showed that wireguard can save the banned ip.
I'm sure my IP is already dead in China.
not only the SSH is,but also cannot open my blog without VPN like lantern.
In fact,I have set up a wireguard which is teached by the document.But I can't use it.Im not sure if I make some mistake on it!
I surely want to know: "if my IP banned from great fire wall,can I setup wireguard to use?
I feel sorry with my Poor English.
老哥们，我IP给墙了还能用这个救吗？
我根据逗比的文档搭了一个没成功，呜呜呜，机器已被墙，用蓝灯上的ssh

**Comment by l-n-s** [comment]
Hi, I'm not sure. 

WireGuard doesn't have any obfuscation to hide from the GFW, it can only work while censors don't know about it. When the protocol will get more popular, they will learn how to ban it.

**Comment by TKBSTMYN** [comment]
@l-n-s thanks,my bro.
 may they think it can disturbing the gfw, causing it's a new type of working style.
