### ISSUE TITLE
UFW

### ISSUE THREAD

**Issue by canusuck** [l-n-s/wireguard-install#40]
After installing UFW, I encounter a problem
```sh
root@debian:~# sudo ufw disable && sudo ufw enable
Firewall stopped and disabled on system startup
Command may disrupt existing ssh connections. Proceed with operation (y|n)? y
ERROR: problem running ufw-init
ip6tables-restore: line 2 failed
```

I want to block ICMP traffic

add to /etc/ufw/before.rules
```
-A ufw-before-input -p icmp --icmp-type echo-request -j DROP
```
or 
```
#-A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT
```

**Comment by l-n-s** [comment]
I don't know anything about ufw. This script set up iptables rules and save them to /etc/iptables/rules.v4, it also uses `iptables-persistent` package to restore those rules after reboot.
