### ISSUE TITLE
Removing Clients - IP Not Reused

### ISSUE THREAD

**Issue by f1yankees** [l-n-s/wireguard-install#45]
First off, great script and thanks so much for putting this together.

Can you remove clients with the script?  When I manually remove a client with "wg set wg0 peer 'pubkey' remove" I notice that the script does not realize I have removed the client.  The IP does not get reused.  Whatever client I add next gets an incremental IP, but only if available.

**Comment by l-n-s** [comment]
There is no such functionality in the script. You will need to manually remove corresponding client section from the config file `/etc/wireguard/wg0.conf`
