### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by mehdi198080** [l-n-s/wireguard-install#46]
would you please advise me how could I uninstall in debian 9 ?

**Comment by l-n-s** [comment]
Remove wireguard package and delete iptables rules.

**Comment by mehdi198080** [comment]
I did bit I face with these error after I want reinstall wireguard 

wireguard-install.sh: line 175: wg: command not found
wireguard-install.sh: line 176: wg: command not found
wireguard-install.sh: line 200: wg: command not found
