### ISSUE TITLE
What is the script doing to my iptables ? Will it mess up my existing iptables config?

### ISSUE THREAD

**Issue by patoshii** [l-n-s/wireguard-install#50]
I see that there are a bunch of iptable commands in the script. What is it doing exactly? I'm worried that it might messup my existing iptables setup. Is it just adding in new rules ONLY for wireguard ports and not touching anything else? Reason why I ask is because I have a custom ssh port of 3333 and don't want that overwritten. thanks!

**Comment by l-n-s** [comment]
Yes it will add iptables rules to route your traffic. Just grep it

    grep iptables wireguard-install.sh
