### ISSUE TITLE
Possible copyright violation

### ISSUE THREAD

**Issue by XelNika** [l-n-s/wireguard-install#54]
[This commit](https://github.com/complexorganizations/wireguard-install/commit/02bb560688c487f715caa54d2ed680400a67eec9) contains a lightly modified version of your script with your name removed. Since this repository is MIT licensed, that could be a copyright violation. The link to this repo has also been removed in a later commit.

**Comment by l-n-s** [comment]
I know about this repository. To be honest, this person and his actions doesn't deserve any attention. Thanks :)
