### ISSUE TITLE
Error message during setup

### ISSUE THREAD

**Issue by hendryque** [l-n-s/wireguard-install#7]
Tried to install WG with the script. After I enter the name of the client, I get this error message:

wireguard-install.sh: Zeile 170: -4: Teilstring-Ausdruck < 0

This happens regardless what I enter as the client name.
Server is a Linux box with Debian 9.

Is there anything I can do here?

**Comment by hendryque** [comment]
Should be

wireguard-install.sh: Line 170: -4: Substring-Expression < 0

**Comment by l-n-s** [comment]
Great, thanks. I'll try to fix it soon.

**Comment by OhioVR** [comment]
I had this problem when I followed someone else's tutorial and came here hoping to find the solution. The error went away when I removed the /etc/wireguard/wg0.conf and started over

**Comment by l-n-s** [comment]
@hendryque actually, I can't understand, what can be the issue. Can you send your config file which causes error? /etc/wireguard/wg0.conf (replace your keys with XXX).

**Comment by l-n-s** [comment]
OK, this is basically the same problem as #16
